### ISSUE TITLE
Error running download_data.py

### ISSUE THREAD

**Issue by seckeymaker** [pytroll/tutorial-satpy-half-day#11]
Hello 

I must be missing something. when running "download_data.py", I receive an error line 6 in <module> import requests.
"ModuleNotFoundError: no module named'requests' "

is this requests module supposed to be in the original github files?

thank you,
Jim

**Comment by djhoese** [comment]
Looks like that dependency is missing from the `environment.yaml`. I make a quick fix. Thanks for filing the bug report.

**Comment by djhoese** [comment]
I'm building the new image now for the binder version of the environment. Looks like `requests` did exist in the installation instructions (https://github.com/pytroll/tutorial-satpy-half-day/blob/main/INSTALL.md), but was missing from the binder environment. Thanks again.

**Comment by seckeymaker** [comment]
Thank you for the quick response.

**Comment by djhoese** [comment]
...actually looks like Pangeo binder is down right now. We'll have to wait for it to come back up to really test this.

**Comment by seckeymaker** [comment]
Ok, thanks for the update.
