### ISSUE TITLE
02_reading.ipynb issue

### ISSUE THREAD

**Issue by ve2fxl** [pytroll/tutorial-satpy-half-day#2]
Hi, just to let you know that there is 2 minor errors in 02_reading.ipynb. The following table:

Channel | Wavelength | Resolution
-- | -- | --
C01 | 0.47µm | 1000m
C02 | 0.64µm | 250m   <-- this should be 500m
C03 | 0.64µm | 1000m <-- this should be 0.86µm
C04 | 1.37µm | 2000m
C05 | 1.60µm | 1000m
C06 | 2.20µm | 2000m
C07 | 3.90µm | 2000m
C08 | 6.20µm | 2000m
C09 | 6.90µm | 2000m
C10 | 7.30µm | 2000m
C11 | 8.40µm | 2000m
C12 | 9.60µm | 2000m
C13 | 10.30µm | 2000m
C14 | 11.20µm | 2000m
C15 | 12.30µm | 2000m
C16 | 13.30µm | 2000m

Thanks for your time and this great notebook!

Luc VE2FXL

**Comment by djhoese** [comment]
Thanks. This should be fixed in the master branch now.

**Comment by ve2fxl** [comment]
Thanks David
