### ISSUE TITLE
Satpy is not importable

### ISSUE THREAD

**Issue by rishisama0** [pytroll/tutorial-satpy-half-day#8]
Hello, I'm trying to download and  install the data and all the necessary files as shown in SETUP part. 

my command python download_data.py is showing as success 
but while executing the command  python test_install.py
I'm getting the following error 

FAIL: Satpy is not importable
Traceback (most recent call last):
  File "test_install.py", line 14, in <module>
    from satpy.config import check_satpy
ModuleNotFoundError: No module named 'satpy.config' 

Can you help me with this ?

**Comment by djhoese** [comment]
Oh sorry! The `check_satpy` function has been moved to `satpy.utils` due to changes in how satpy does configuration. If you edit the script to say `from satpy.utils import check_satpy` then the rest of it *should* work.

**Comment by rishisama0** [comment]
wow! that worked thank you :D
